### ISSUE TITLE
Something errors occured when using function subtract.

### ISSUE THREAD

**Issue by chamip** [Limeoats/BigNumber#10]
When I test function subtract using a example in main.cpp like ```assert((BigNumber("-100") - BigNumber("-5")) == -95);```，assertion failed.
<img width="1012" alt="assertion failed with func subtract" src="https://github.com/Limeoats/BigNumber/assets/42117528/9c7320ac-344a-4b6f-8738-9038840b51dd">

**Comment by chamip** [comment]
@Limeoats please check my pull request.

**Comment by Limeoats** [comment]
Merged #9
