### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by driftee** [Limeoats/BigNumber#4]
If I want to construct the class with a big integer without ""(quotation marks),like
BigNumber a = 1234567898765432123456789;
something like this. What should I do?

**Comment by kuruk-mm** [comment]
The construct operador allow you to initialize with a "long long" data type
`BigNumber(long long number);`

So... the data type range of long long is -9223372036854775807 to 9223372036854775807

If you want a number larger than that, you need to use quoting marks.
