### ISSUE TITLE
Maybe a bug when calculate bignumer divide

### ISSUE THREAD

**Issue by luoyhang003** [Limeoats/BigNumber#5]
You could try this:

```cpp
    BigNumber big256(hex2dec.Convert("ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"));
    BigNumber target = big256 / BigNumber("1");
```

it seems trap into an endless loop.

**Comment by killerdevildog11** [comment]
I am also having issues on this same problem

**Comment by Limeoats** [comment]
Can you please elaborate on the issue you are running into? You're experiencing an infinite loop when using the divide method?
